# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Publish and export"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  publish:
     runs-on: ubuntu-latest
     steps:
        - name: Publish gem

          uses: dawidd6/action-publish-gem@v1.2.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
  export:
   needs: publish
   runs-on: ubuntu-latest
   steps:
     - uses: actions/upload-artifact@v2
       with:
         name: blogcog
         path: https://github.com/${{ github.repository }}.git
  check-http:
    needs: publish
    runs-on: windows-latest
    steps:
      - run: |
         $HTTP_Request = [System.Net.WebRequest]::Create('https://rubygems.pkg.github.com')
         If ($HTTP_Status -eq 200) { Write-Host "Site is OK." } Else { Write-Host "::error::GPR may be down, please check!" }
