# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: Test with Ruby ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.7.4, 2.7.5, 3.0.0-preview1, 3.0.0-preview2, 3.0.0-rc1, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.1.0-preview1, 3.1.0]
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add or replace dependency steps here
      - name: Install Ruby ${{ matrix.ruby-version }} and your gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      - run: |
         sudo apt-get install rails
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake

  lint:
    name: Lint with Ruby ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.7.4, 2.7.5, 3.0.0-preview1, 3.0.0-preview2, 3.0.0-rc1, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.1.0-preview1, 3.1.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby ${{ matrix.ruby-version }} and your gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      - run: |
         sudo apt-get install rails
         sudo apt-get install rubocop
      # Add or replace any other lints here
      - name: Lint Ruby files
        run: rubocop --parallel
  publish:
     needs: [test, lint]
     runs-on: ubuntu-latest
     steps:
        - name: Publish gem

          uses: dawidd6/action-publish-gem@v1.2.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
  export:
   needs: [publish, test]
   runs-on: ubuntu-latest
   steps:
     - uses: actions/upload-artifact@v2
       with:
         name: blogcog
         path: https://github.com/${{ github.repository }}.git
  check-http:
    needs: publish
    runs-on: windows-latest
    steps:
      - run: |
         $HTTP_Request = [System.Net.WebRequest]::Create('https://rubygems.pkg.github.com')
         If ($HTTP_Status -eq 200) { Write-Host "Site is OK." } Else { Write-Host "::error::GPR may be down, please check!" }
